config/routes.rb
Rails.application.routes.draw do
  resources :persons
  resources:users
  resources :goods
end

app/models/book.rb
class Person < ActiveRecord::Base
end

app/models/good.rb
class Good  < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  #protect_from_forgery with: :exception
end

app/controllers/goods_controller.rb
class GoodsController < ApplicationController

  before_action :get_by_id,:only =>[:show,:destroy,:edit,:update]
  layout 'a'
  def index
    @goods = Good.all
    render :layout => 'a'
  end

  def new
    @good = Good.new
    render :layout => 'b'
  end

  def create
    puts "==params is: "
    Good.create :name => params[:name],
    :price => params[:price]
    redirect_to goods_path
  end

  def edit
  end

  def update
    #@goods.name = params[:name]
    #@goods.price = params[:price]
    #@goods.save

    @good.update params[:good]

    redirect_to goods_path

    #redirect_to :back
  end

  def show
  end

  def destroy
    @good.delete
    redirect_to goods_path
  end

  private
  def get_by_id
    @good = Good.find params[:id]
  end
end

app/controllers/persons_controller.rb
class PersonsController < ApplicationController

  def index
    @persons = Person.all
  end

  def new
  end

 # def create
 # end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/books/index.html.erb
<h3> book</h3>

app/views/goods/_form.html.erb
<%= form_for @good do |f| %>

<%# form_for '/goods/new' do |f| %>
<%# form_for '/goods/1/edit' do |f| %>
  名称: <%= f.text_field :name %> <br/>
  价格<%= f.text_field :price %><br/>
  <%= f.submit %>

<% end %>

app/views/goods/edit.html.erb
<hr>编辑页面</h3>


<%= render :partial => 'form' %>

性别： <%= select_tag"sex",options_for_select([['male','男'],['female','女']]) %> <br/>
<hr/>

<%= form_tag good_path(:id => @good.id),:method =>'PUT' do %>
  名称：<%= text_field_tag 'good[name]',@good.name %> <br/>
  价格：<%= text_field_tag 'good[price]',@good.price %> <br/>
  <%=submit_tag %>
<% end %>

app/views/goods/index.html.erb
<h3>新建页面</h3>

<table>
  <tr>
    <td>名称</td>
    <td>价格</td>
    <td>操作</td>
  <tr>

  <%= @goods.each do |goods| %>
    <tr>
      <td>
        <%= link_to goods.name,goods %>
      </td>
      <td>
        <%=goods.price %>
      </td>
      <td>
        <%= link_to "编辑", edit_good_path(:id =>goods.id) %>
        <%= link_to "删除",goods,:method => :delete %>
      </td>
    </tr>
  <% end %>
</table>

<br/>

<%= link_to "新建", new_good_path %>

app/views/goods/new.html.erb
<h3>新建页面</h3>

<%= render :partial =>"form" %>


<!--
<form action='/goods' method=POST>


  name:  <input type='text' name='name'/> <br/>
  price:  <input type='text' name='price'/> <br/>

  <input type='submit' />
</form>
-->

app/views/goods/show.html.erb
<h3>详情页面</h3>

name: <%= @good.name %><br/>
price:<%= @good.price %><br/>

<%= link_to'列表页面',goods_path %>

app/views/layouts/a.html.erb
<head>
  <title>
    我是布局A
  </title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

  <%= yield %>

  <div>
  </div>
</body>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TestFruits</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/layouts/b.html.erb
<head>
<title>
  我是布局B
</title>
<div>
</div>
<%= csrf_meta_tags %>
</head>
<body>

  <%= yield %>
</body>